from abc import ABC, abstractmethod
from eggreader import LocustP3File

class DataTransform(ABC):
    
    __file = None
    __verbose = True

    # Open the file in the format generated by eggreader, LocustP3File
    def Open(self, egg_file):
        assert isinstance(egg_file, LocustP3File), "input must be a LocustP3File"
        self.__file = egg_file
        # ToDo implement this in the abstract class itself.
        print('placeholder: File opened successfully')
        pass

    # The transformation class is implemented by the subclasses.
    @abstractmethod    
    def Transform(self):
        pass

    # Safe the file?    
    def Close(self):
        # ToDo implement this in the abstract class itself.
        print('placeholder: File closed successfully')
        pass